#!/usr/bin/env python3
"""Resolve generated Gradle dependency paths from this checkout's Cargo graph."""
import json
from pathlib import Path
import subprocess

root = Path(__file__).resolve().parents[2]
metadata = json.loads(subprocess.check_output(
    ['cargo', 'metadata', '--locked', '--format-version', '1', '--filter-platform', 'aarch64-linux-android'], cwd=root, text=True))
packages = {p['name']: Path(p['manifest_path']).parent for p in metadata['packages']}
project = Path(__file__).resolve().parent / 'gen/android'
modules = [('tauri-android', 'tauri', 'mobile/android'),
           ('tauri-plugin-dialog', 'tauri-plugin-dialog', 'android'),
           ('tauri-plugin-fs', 'tauri-plugin-fs', 'android')]
lines = ['// Generated by prepare_gradle.py; do not commit machine paths.']
for module, package, suffix in modules:
    directory = (packages[package] / suffix).as_posix()
    escaped = directory.replace('\\', '\\\\').replace("'", "\\'")
    lines += [f"include ':{module}'",
              f"project(':{module}').projectDir = new File('{escaped}')"]
(project / 'tauri.settings.gradle').write_text('\n'.join(lines) + '\n')
(project / 'app/tauri.build.gradle.kts').write_text(
    '// Generated by prepare_gradle.py\nval implementation by configurations\ndependencies {\n' +
    ''.join(f'    implementation(project(":{module}"))\n' for module, _, _ in modules) + '}\n')
version = next(p['version'] for p in metadata['packages'] if p['name'] == 'mausfer-android')
(project / 'app/tauri.properties').write_text(
    f'tauri.android.versionName={version}\ntauri.android.versionCode=1000\n')
print('Android Gradle dependency paths prepared.')
