//! High-level remote (P2P) transfer orchestration.
//!
//! Flow (matches `使用方法.md`):
//! 1. The **receiver** generates a room code and waits.
//! 2. The **sender** joins with that code and offers; the receiver answers.
//! 3. After the WebRTC connection is established, the existing framed
//!    transfer protocol runs over the DataChannel.
//!
//! Both roles are testable on loopback with a real in-process signaling
//! server and two peer connections.

use crate::config::Config;
use crate::discovery::DeviceInfo;
use crate::p2p::{self, P2pSession, P2pSignalEvent};
use crate::signaling::{SessionDescription, SignalClient, SignalMessage};
use crate::transfer::{FileMetadata, ReceiveReport, SendReport};
use std::path::Path;
use std::time::Duration;

const SEND_PEER_TIMEOUT: Duration = Duration::from_secs(60);
const RECEIVE_CODE_LIFETIME: Duration = Duration::from_secs(15 * 60);
const SIGNAL_REPLY_TIMEOUT: Duration = Duration::from_secs(60);

/// Result of a remote P2P transfer.
#[derive(Debug, Clone)]
pub enum RemoteReport {
    Sent(SendReport),
    Received(ReceiveReport),
}

/// Options for a remote P2P transfer.
#[derive(Clone)]
pub struct RemoteOptions {
    /// Existing 16-character room code generated by the receiver.
    pub room_code: String,
    /// Self-hosted WebSocket signaling URL configured by the user.
    pub signal_url: String,
    /// This device's identity.
    pub device: DeviceInfo,
}

/// Sender role: joins the receiver's room, offers, and sends `path`.
pub async fn remote_send(
    config: &Config,
    options: RemoteOptions,
    path: &Path,
) -> Result<(RemoteReport, String), String> {
    remote_send_with_progress(config, options, path, |_| {}).await
}

/// Sender with diagnostic phase notifications shared by all native shells.
pub async fn remote_send_with_progress(
    config: &Config,
    options: RemoteOptions,
    path: &Path,
    progress: impl Fn(&str) + Send + Sync,
) -> Result<(RemoteReport, String), String> {
    remote_send_observed(config, options, path, progress, |_| {}).await
}

pub async fn remote_send_observed(
    config: &Config,
    options: RemoteOptions,
    path: &Path,
    progress: impl Fn(&str) + Send + Sync,
    transfer_progress: impl FnMut(crate::transfer::TransferProgress) + Send + 'static,
) -> Result<(RemoteReport, String), String> {
    let code = options.room_code.clone();
    if !crate::signaling::valid_room_code(&code) {
        return Err(format!("连接码无效：{code}（应为 XXXX-XXXX-XXXX-XXXX）"));
    }

    // Hash before joining the room, on a blocking worker. Large files must
    // neither stall the async runtime nor consume the peer's reply timeout.
    let metadata_path = path.to_path_buf();
    let meta = tokio::task::spawn_blocking(move || {
        FileMetadata::for_file(
            &metadata_path,
            crate::transfer::new_transfer_id(),
            crate::transfer::DEFAULT_CHUNK_SIZE,
        )
    })
    .await
    .map_err(|e| format!("metadata task failed: {e}"))?
    .map_err(|e| e.to_string())?;

    progress("正在连接信令服务器");
    let mut signal = SignalClient::connect(&options.signal_url).await?;
    progress("信令已连接，正在等待对方加入");
    let mut device = options.device.clone();
    // Keep the base id but make the signaling *presence* id role-distinct so
    // two instances of the same device (sender + receiver) never look like
    // the same peer to the room.
    device.id = format!("{}:send", options.device.id);
    signal.send(&SignalMessage::Join {
        room: code.clone(),
        device: device.clone(),
    })?;
    wait_peer(&mut signal, &device.id, SEND_PEER_TIMEOUT).await?;

    progress("已配对，正在收集直连地址");
    // Host (offer) side.
    let (signal_tx, mut signal_rx) = tokio::sync::mpsc::unbounded_channel::<P2pSignalEvent>();
    let session = std::sync::Arc::new(P2pSession::create_offer_session(config, signal_tx).await?);

    // Relay the local offer to the peer over signaling.
    let offer = take_local_description(&mut signal_rx).await?;
    progress(&candidate_summary(&offer));
    signal.send(&SignalMessage::Offer { sdp: offer.clone() })?;

    // Wait for the answer.
    let answer = tokio::time::timeout(SIGNAL_REPLY_TIMEOUT, async {
        loop {
            match signal.recv().await? {
                SignalMessage::Answer { sdp } => return Ok(sdp),
                SignalMessage::Error { message } => return Err(message),
                _ => continue,
            }
        }
    })
    .await
    .map_err(|_| "等待对方响应超时".to_string())??;
    session.set_remote_description(&answer).await?;

    // ICE candidates are already included in the gathered SDP.
    progress("正在建立文件数据通道");
    wait_connected(&session, &mut signal).await?;

    let dc = session
        .local_channel()
        .ok_or_else(|| "data channel unavailable".to_string())?;
    // Use the session-owned inbound queue. It starts capturing as soon as the
    // DataChannel is created, so an early ACCEPT/COMPLETE frame cannot be
    // lost between channel-open and transfer startup.
    let io = session.wrap_channel(dc).await?;

    // The transfer protocol is blocking; run it on a blocking thread so the
    // runtime's workers stay free for the WebRTC internals.
    progress("数据通道已连接，正在发送文件");
    let path_owned = path.to_path_buf();
    let report = tokio::task::spawn_blocking(move || {
        let mut io = io;
        crate::transfer::send_file_with_progress(&mut io, &path_owned, &meta, transfer_progress)
    })
    .await
    .map_err(|e| format!("transfer task failed: {e}"))?
    .map_err(|e| e.to_string())?;

    progress("文件传输与校验完成");
    session.close().await;
    Ok((RemoteReport::Sent(report), code))
}

/// Receiver (guest) role: joins an existing room, answers, receives into
/// `download_dir`.
pub async fn remote_recv(
    config: &Config,
    options: RemoteOptions,
    download_dir: &Path,
) -> Result<RemoteReport, String> {
    remote_recv_with_progress(config, options, download_dir, |_| {}).await
}

/// Receiver with diagnostic phase notifications shared by all native shells.
pub async fn remote_recv_with_progress(
    config: &Config,
    options: RemoteOptions,
    download_dir: &Path,
    progress: impl Fn(&str) + Send + Sync,
) -> Result<RemoteReport, String> {
    remote_recv_observed(config, options, download_dir, progress, |_| {}).await
}

pub async fn remote_recv_observed(
    config: &Config,
    options: RemoteOptions,
    download_dir: &Path,
    progress: impl Fn(&str) + Send + Sync,
    transfer_progress: impl FnMut(crate::transfer::TransferProgress) + Send + 'static,
) -> Result<RemoteReport, String> {
    if options.room_code.is_empty() || !crate::signaling::valid_room_code(&options.room_code) {
        return Err(format!(
            "连接码无效：{}（应为 XXXX-XXXX-XXXX-XXXX）",
            options.room_code
        ));
    }
    progress("正在连接信令服务器");
    let mut signal = SignalClient::connect(&options.signal_url).await?;
    progress("信令已连接，正在等待对方加入");
    let mut device = options.device.clone();
    // Role-distinct presence id (see remote_send).
    device.id = format!("{}:recv", options.device.id);
    signal.send(&SignalMessage::Join {
        room: options.room_code.clone(),
        device: device.clone(),
    })?;
    wait_peer(&mut signal, &device.id, RECEIVE_CODE_LIFETIME).await?;

    progress("已配对，正在等待发送方协商");
    // Wait for the offer, then answer.
    let offer = tokio::time::timeout(SIGNAL_REPLY_TIMEOUT, async {
        loop {
            match signal.recv().await? {
                SignalMessage::Offer { sdp } => return Ok(sdp),
                SignalMessage::Error { message } => return Err(message),
                _ => continue,
            }
        }
    })
    .await
    .map_err(|_| "等待发送方协商超时".to_string())??;

    let (signal_tx, mut signal_rx) = tokio::sync::mpsc::unbounded_channel::<P2pSignalEvent>();
    let session =
        std::sync::Arc::new(P2pSession::accept_offer_session(config, &offer, signal_tx).await?);

    // Relay the local answer to the peer over signaling.
    let answer = take_local_description(&mut signal_rx).await?;
    progress(&candidate_summary(&answer));
    signal.send(&SignalMessage::Answer {
        sdp: answer.clone(),
    })?;

    progress("正在建立文件数据通道");
    wait_connected(&session, &mut signal).await?;

    let dc = session.accept_channel().await?;
    let io = session.wrap_channel(dc).await?;

    progress("数据通道已连接，正在接收文件");
    let recv_dir = download_dir.to_path_buf();
    std::fs::create_dir_all(download_dir).map_err(|e| e.to_string())?;
    let report = tokio::task::spawn_blocking(move || {
        let mut io = io;
        crate::transfer::receive_file_with_progress(&mut io, &recv_dir, transfer_progress)
    })
    .await
    .map_err(|e| format!("transfer task failed: {e}"))?
    .map_err(|e| e.to_string())?;

    progress("文件传输与校验完成");
    session.close().await;
    Ok(RemoteReport::Received(report))
}

fn candidate_summary(description: &SessionDescription) -> String {
    let count = |kind: &str| {
        description
            .sdp
            .lines()
            .filter(|line| {
                line.starts_with("a=candidate:")
                    && line
                        .split_whitespace()
                        .collect::<Vec<_>>()
                        .windows(2)
                        .any(|pair| pair == ["typ", kind])
            })
            .count()
    };
    format!(
        "网络候选地址：本地 {}，STUN {}，TURN {}",
        count("host"),
        count("srflx"),
        count("relay")
    )
}

/// Keep consuming signaling while connecting so peer departure or server
/// shutdown is reported immediately instead of turning into an ICE timeout.
async fn wait_connected(session: &P2pSession, signal: &mut SignalClient) -> Result<(), String> {
    tokio::select! {
        result = session.wait_connected(p2p::CONNECT_TIMEOUT) => result.map_err(|e|
            format!("文件直连失败（信令已连接）: {e}。请检查双方网络；公共 STUN 无法穿透的网络需要 TURN 中继")),
        error = async {
            loop {
                match signal.recv().await {
                    Err(error) | Ok(SignalMessage::Error { message: error }) => break error,
                    Ok(SignalMessage::PeerLeft) => break "对方已断开连接".into(),
                    Ok(SignalMessage::Ice {candidate, sdp_mid, sdp_mline_index}) => {
                        if let Err(error) = session.add_remote_candidate(&candidate, sdp_mid, sdp_mline_index).await { break error; }
                    }
                    _ => {}
                }
            }
        } => Err(error),
    }
}

/// Wait for `PeerJoined` from the signaling server (ignore self-echoes).
async fn wait_peer(
    signal: &mut SignalClient,
    own_id: &str,
    timeout: Duration,
) -> Result<(), String> {
    tokio::time::timeout(timeout, async {
        loop {
            match signal.recv().await? {
                SignalMessage::PeerJoined { peer } => {
                    if peer.id != own_id {
                        return Ok(());
                    }
                }
                SignalMessage::Error { message } => return Err(message),
                _ => continue,
            }
        }
    })
    .await
    .map_err(|_| "连接码已过期或对方未上线".to_string())?
}

/// Take the local session description from the peer-connection event channel
/// (the offer or answer produced by [`P2pSession`]).
async fn take_local_description(
    signal_rx: &mut tokio::sync::mpsc::UnboundedReceiver<P2pSignalEvent>,
) -> Result<SessionDescription, String> {
    tokio::time::timeout(std::time::Duration::from_secs(30), async {
        loop {
            match signal_rx.recv().await {
                Some(P2pSignalEvent::LocalDescription(sdp)) => return Ok(sdp),
                Some(P2pSignalEvent::LocalIce { .. }) => continue,
                None => return Err("peer connection event channel closed".to_string()),
            }
        }
    })
    .await
    .map_err(|_| "timed out waiting for local description".to_string())?
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::signaling::SignalingServer;
    use std::sync::Arc;

    fn random_file(dir: &std::path::Path, size: usize) -> std::path::PathBuf {
        std::fs::create_dir_all(dir).unwrap();
        let path = dir.join("payload.bin");
        let mut data = vec![0u8; size];
        let mut seed: u64 = 0xFEED_FACE_CAFE_BEEF;
        for b in data.iter_mut() {
            seed ^= seed << 13;
            seed ^= seed >> 7;
            seed ^= seed << 17;
            *b = (seed & 0xFF) as u8;
        }
        std::fs::write(&path, &data).unwrap();
        path
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 4)]
    async fn full_remote_transfer_via_signaling() {
        // Full remote P2P transfer over a real signaling server.
        // NOTE: creating both peer connections in ONE process as concurrent
        // tokio tasks is unstable with webrtc-rs on loopback; the supported
        // production topology is one process per device (each side creates
        // exactly one RTCPeerConnection), which this sequential test emulates
        // and the CLI/desktop shells use in practice.
        let server = Arc::new(SignalingServer::new());
        let bound = server
            .clone()
            .serve("127.0.0.1:0".parse().unwrap())
            .await
            .unwrap();
        let signal_url = format!("ws://{bound}");
        let config = Config {
            // This test validates signaling plus WebRTC on loopback. Avoid a
            // public STUN dependency that can make offline CI time out.
            stun_url: String::new(),
            ..Config::default()
        };
        let code = "AABBCCDDEEFFGGHH".to_string();

        let dir = std::env::temp_dir().join(format!(
            "mausfer-test-remote-{}-{}",
            std::process::id(),
            crate::transfer::new_transfer_id()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let src = random_file(&dir, 250_000);
        let recv_dir = dir.join("recv");
        std::fs::create_dir_all(&recv_dir).unwrap();

        let mut signal_r = SignalClient::connect(&signal_url).await.unwrap();
        signal_r
            .send(&SignalMessage::Join {
                room: code.clone(),
                device: DeviceInfo::new("rr", "RR", 1, "0.1"),
            })
            .unwrap();
        let mut signal_s = SignalClient::connect(&signal_url).await.unwrap();
        signal_s
            .send(&SignalMessage::Join {
                room: code.clone(),
                device: DeviceInfo::new("ss", "SS", 2, "0.1"),
            })
            .unwrap();
        wait_peer(&mut signal_r, "rr", Duration::from_secs(5))
            .await
            .unwrap();
        wait_peer(&mut signal_s, "ss", Duration::from_secs(5))
            .await
            .unwrap();

        let (s_tx_r, mut s_rx_r) = tokio::sync::mpsc::unbounded_channel::<P2pSignalEvent>();
        let (s_tx_s, mut s_rx_s) = tokio::sync::mpsc::unbounded_channel::<P2pSignalEvent>();
        let session_s = std::sync::Arc::new(
            P2pSession::create_offer_session(&config, s_tx_s)
                .await
                .unwrap(),
        );
        let offer = take_local_description(&mut s_rx_s).await.unwrap();
        signal_s.send(&SignalMessage::Offer { sdp: offer }).unwrap();
        let offer_rx = loop {
            match signal_r.recv().await.unwrap() {
                SignalMessage::Offer { sdp } => break sdp,
                _ => continue,
            }
        };
        let session_r = std::sync::Arc::new(
            P2pSession::accept_offer_session(&config, &offer_rx, s_tx_r)
                .await
                .unwrap(),
        );
        let answer = take_local_description(&mut s_rx_r).await.unwrap();
        signal_r
            .send(&SignalMessage::Answer { sdp: answer })
            .unwrap();
        let answer_rx = loop {
            match signal_s.recv().await.unwrap() {
                SignalMessage::Answer { sdp } => break sdp,
                _ => continue,
            }
        };
        session_s.set_remote_description(&answer_rx).await.unwrap();
        tokio::join!(
            session_s.wait_connected(std::time::Duration::from_secs(20)),
            session_r.wait_connected(std::time::Duration::from_secs(20)),
        )
        .0
        .unwrap();
        session_r
            .wait_connected(std::time::Duration::from_secs(1))
            .await
            .unwrap();

        let dc_s = session_s.local_channel().unwrap();
        let dc_r = session_r.accept_channel().await.unwrap();
        let mut io_s = session_s.wrap_channel(dc_s).await.unwrap();
        let mut io_r = session_r.wrap_channel(dc_r).await.unwrap();

        let handle = tokio::task::spawn_blocking(move || {
            let meta = crate::transfer::FileMetadata::for_file(
                &src,
                crate::transfer::new_transfer_id(),
                crate::transfer::DEFAULT_CHUNK_SIZE,
            )
            .unwrap();
            crate::transfer::send_file(&mut io_s, &src, &meta).unwrap()
        });
        let report_r = tokio::task::spawn_blocking(move || {
            crate::transfer::receive_file(&mut io_r, &recv_dir).unwrap()
        });
        let sent = handle.await.unwrap();
        let received = report_r.await.unwrap();
        assert_eq!(sent.bytes_sent, 250_000);
        assert_eq!(received.bytes_written, 250_000);
        assert_eq!(sent.sha256, received.sha256);
        assert!(received.saved_path.exists());

        let _ = std::fs::remove_dir_all(&dir);
    }
}
